#!/usr/bin/env bash
#===============================================================================
# Script name (shortname) - Short description for script
# v0.0.1- <year>-<month>-<day>
# Licensed under the MIT license
#
# Long description of script
# 
# Copyright (c) <year> <copyright-holder>
# <url>
#
# Notes
#-------------------------------------------------------------------------------
# Quickstart
# Setup information
# Changelog
# ToDo
# Known bugs
#
# Based on BASH4 Boilerplate 20170818-dev and BASH3 Boilerplate v2.3.0
#===============================================================================
# Init section
#===============================================================================
# Allowing aliases
shopt -s expand_aliases
# Exit on error 
set -o errexit 
# Exit on error inside any functions or subshells
set -o errtrace
 # Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset 
# Catch the error when mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail 
# Turn on traces, useful while debugging but commented out by default
#set -o xtrace

#===============================================================================
# Globals section
#===============================================================================

#-------------------------------------------------------------------------------
# Environment variables
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Localization
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Usage information
#-------------------------------------------------------------------------------

#===============================================================================
# Functions section
#===============================================================================

#===============================================================================
# Main section
#===============================================================================

#===============================================================================
# END OF FILE
#===============================================================================
