#!/usr/bin/env bash
#===============================================================================
# Standalone script installer (script_install)
# Licensed under the MIT license
#
# This file can install bash-script and it's dependencies from a specified
# folder, using install.ini file. 
# It is part of BASH3 Boilerplate by krisztianmukli project.
# 
# Copyright (c) 2018 Krisztián Mukli
# https://www.github.com/krisztianmukli/bash3boilerplate
#
# Notes
#-------------------------------------------------------------------------------
# Quickstart
#
#   script_install -s sourcedir [-t targetdir | -c]
#
# Setup information
# Changelog
# ToDo
# Known bugs and limitations
#
# * When targetfile unwritable and cp ask 'try anyway?' and user choose No, 
#   it will exit 0, and script_install say installation was succesful.
# * Preinstall and postinstall script must be locate in source directory
#
# Based on BASH3 Boilerplate by krisztianmukli v1.0.0
#===============================================================================
# Init section
#===============================================================================
# Exit on error 
set -o errexit 
# Exit on error inside any functions or subshells
set -o errtrace
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset 
# Catch the error when mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
set -o pipefail 
# Turn on traces, useful while debugging but commented out by default
#set -o xtrace

#===============================================================================
# Globals section
#===============================================================================

#-------------------------------------------------------------------------------
# Environment variables
#-------------------------------------------------------------------------------
if [[ "${BASH_SOURCE[0]}" != "${0}" ]] ; then
  __si_srcd=1
  if [[ "${BASH_SOURCE[1]+x}" ]]; then
    [[ "${BASH_SOURCE[1]}" = "${0}" ]] && __si_srcd=0
    __si_tmp_source_idx=1
  fi
  [[ "${__si_usage+x}" ]] && __si_external_usage=1
else
  __si_srcd=0
  [[ "${__si_usage+x}" ]] && unset -v __si_usage
  [[ "${__si_helptext+x}" ]] && unset -v __si_helptext
fi
__si_dir="$(cd "$(dirname "${BASH_SOURCE[${__si_tmp_source_idx:-0}]}")" && pwd)"
__si_file="${__si_dir}/$(basename "${BASH_SOURCE[${__si_tmp_source_idx:-0}]}")"
__si_base="$(basename "${__si_file}" .sh)"
__si_user_home="$([[ "${SUDO_USER+x}" ]] && getent passwd "${SUDO_USER}" | cut -d: -f6 || echo "$HOME")"

LOG_LEVEL="${LOG_LEVEL:-6}" # 7 = debug -> 0 = emergency
LOG_TIMEZONE="${LOG_TIMEZONE:-1}" # 0 = UTC, otherwise local
NO_COLOR="${NO_COLOR:-}"    # true = disable color. otherwise autodetected

#-------------------------------------------------------------------------------
# Sourced files
#-------------------------------------------------------------------------------
export PATH="${__si_dir}:${__si_dir}/lib:$PATH"
source log.sh || (echo "Fatal error: Cannot find log.sh!"; exit 1)
source os_detection.sh || (echo "Fatal error: Cannot find os_detection.sh!"; exit 1)
source display_info.sh || (echo "Fatal error: Cannot find display_info.sh!"; exit 1)
source ini_val.sh || (echo "Fatal error: Cannot find ini_val.sh!"; exit 1)
source ask.sh || (echo "Fatal error: Cannot find ask.sh!"; exit 1)
source gettext.sh || (echo "Fatal error: Cannot find gettext.sh!"; exit 1)

#-------------------------------------------------------------------------------
# Localization
#-------------------------------------------------------------------------------
__si_localepath=( "${__si_dir}/locale" "${__si_user_home}/.local/share/locale" "/usr/local/share/locale" "/usr/share/locale" )
  for folder in "${__si_localepath[@]}"; do
    if [[ -d "${folder}" ]]; then
      count=$(find "${folder}" -name "${__si_base}.mo" | wc -l )
      if [[ $count -gt 0 ]]; then
        export TEXTDOMAINDIR="${folder}"
        break
      fi
    fi
  done
export TEXTDOMAIN="${__si_base}"

#-------------------------------------------------------------------------------
# Usage 
#-------------------------------------------------------------------------------
[[ "${__si_usage+x}" ]] || __si_usage="$(eval_gettext "Available arguments:

  -c --check-dependencies  Check dependencies of specified script
  -d --debug               Enables debug mode
  -f --force               Forcing commands (e.g. overwrite existing files)
  -h --help                This page
  -i --ini [inifile]       Ini-file using the installation. If not set, installer use [sourcedir]/install.ini
  -n --no-color            Disable color output
  -s --source [sourcedir]  Source dir of script. Default=\"\$(pwd)\"
  -t --target [targetdir]  Target directory. You can use following abbreviations, or specify explicit target:
                           * 'sys', 'system' or 'system-wide' for /usr/local/bin (/usr/local/share/locale for localization)
			   * 'usr', 'user' or 'user-wide' for ~/.local/bin (~/.local/share/locale for localization)
			   If specify explicit targetdir, script libraries and locale will install to that folder.
			   Optional, if not specified, assuming system-wide installation, 
			   fallback to user-wide if there is no root permission.
  -v                       Enable verbose mode, print script as it is executed
  -V --version             Display version and license information")"

[[ "${__si_helptext+x}" ]] || __si_helptext="$(gettext "This command can install bash-script and it's dependencies from a specified
 folder, using install.ini file. 
 It is part of BASH3 Boilerplate by krisztianmukli project.")"
__si_defaulttext="$(gettext "Default")"
__si_requiredtext="$(gettext "Required")"
__si_name="$(gettext "Standalone script installer")"
__si_version="v1.0.0"
__si_license="$(gettext "Licensed under the MIT license")"

#===============================================================================
# Functions section
#===============================================================================
function install_dependencies(){
local missingpkgs="${1:-}"
local force=${2:-0}
local result

debug "$(gettext "Starting package-installation")"
  set +o errexit # Not exit on error, neccesary for logging package-management return codes
  install_pkgs "${missingpkgs}" "${force}" 2>&1 | while read line; do info "${line}"; done;
  result=$?
  set -o errexit # Exit on error
  case $result in 
    0) 
      info "$(eval_gettext "Installation of following dependencies was succesful: \${missingpkgs}")"
      return 0
      ;;
    1)
      warning "$(gettext "No valid packages")"
      return 1
      ;;
    2)
      error "$(gettext "You need higher privileges for installing packages!")"
      return 1
      ;;
    3)
      error "$(eval_gettext "For installing following packages in macOS, you must use Homebrew or Macports: \${missingpkgs}")"
      return 1
      ;;
    4)
      error "$(eval_gettext "Install the following packages from shell in cygwin, must be use apt-cyg, or install them with Cygwin setup.exe: \${missingpkgs}")"
      return 1
      ;;     
    255)
      error "$(eval_gettext "Unknown or unsupported operating system, cannot install following packages: \${missingpkgs}")"
      return 1
      ;;
    *)
      error "$(gettext "Unknown error during installing packages!")"
      return 1
      ;;
  esac
  debug "$(gettext "Finished the package-installation")"
}
#-------------------------------------------------------------------------------
# install_files: Copy files (and it's payloads) from sourcedir to targetdir 
# Arguments:
#   install_files sourcedir targetdir localetargetdir
# Returns:
#   exit 1 if any command was unsuccessful
#-------------------------------------------------------------------------------
function install_files() {
local sourcedir=${1:-}
local libsourcedir="${sourcedir:-}/lib"
local localesourcedir="${sourcedir:-}/locale"
local inifile=${2:-}
local targetdir=${3:-}
local libtargetdir="${targetdir:-}/lib"
local localetargetdir="${4:-}"
local scripts=$( get_ini_val "${inifile}" "install.scripts" )
local libraries=$( get_ini_val "${inifile}" "install.libraries" )
local payloads=$( get_ini_val "${inifile}" "install.payloads" )
local dependencies=$( get_ini_val "${inifile}" "install.dependencies" )
local thirdparties=$( get_ini_val "${inifile}" "install.thirdparties" )
local preinst=$( get_ini_val "${inifile}" "install.preinst" )
local postinst=$( get_ini_val "${inifile}" "install.postinst" )
local force=${5:-0}
local missingpkgs result actpwd

  # Check sourcedir is exists
  [[ ! -d "${sourcedir}" ]] && emergency "$(eval_gettext "Installation unsuccessful: \${sourcedir} is not exists!")"

  # Calling preinstall scripts, if any
  for command in ${preinst}; do
    eval "${command}"
  done

  # Check targetdir is exists, otherwise create it
  [[ ! -d "${targetdir}" ]] && (mkdir "${targetdir}" 2>&- || emergency "$(eval_gettext "Installation unsuccessful: can not create \${targetdir}")")
  # Check targetdir is writable
  [[ ! -w "${targetdir}" ]] && emergency "$(eval_gettext "Installation unsuccessful: \${targetdir} not writable")"
  
  # Check libraries is not empty
  if [[ "${libraries+x}" ]]; then	  
    # Check sourcedir/lib is exists
    [[ -d "${libsourcedir}" ]] || emergency "$(eval_gettext "Installation unsuccessful: \${libsourcedir} is not exists!")"
    # Check targetdir/lib is exists, otherwise create it
    [[ ! -d "${libtargetdir}" ]] && (mkdir "${libtargetdir}" 2>&- || emergency "$(eval_gettext "Installation unsuccessful: can not create \${libtargetdir}")")
    # Check targetdir/lib is writable
    [[ ! -w "${libtargetdir}" ]] && emergency "$(eval_gettext "Installation unsuccessful: \${libtargetdir} not writable")"
  fi

  # Check localedir is exists, if there is locale folder in sourcedir
  if [[ -d "${localesourcedir}" ]]; then
    # Check targetdir is exists, otherwise create it
    [[ ! -d "${localetargetdir}" ]] && (mkdir "${localetargetdir}" 2>&- || emergency "$(eval_gettext "Installation unsuccessful: can not create \${localetargetdir}")")
    # Check targetdir is writable
    [[ ! -w "${localetargetdir}" ]] && emergency "$(eval_gettext "Installation unsuccessful: \${localetargetdir} not writable")"
  fi

  for script in ${scripts}; do
    # Check filename can't pipe to upper directory
    [[ "${script}" = *".."* ]] && emergency "$(eval_gettext "Installation unsuccessful: unsupported filename (\${script})")"
    if [[ "${force}" = "1" ]]; then
	    cp -f "${sourcedir}/${script}" "${targetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
	    cp -f "${sourcedir}/install.ini" "${targetdir}/${script}.ini" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    else
	    cp -i "${sourcedir}/${script}" "${targetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
	    cp -i "${sourcedir}/install.ini" "${targetdir}/${script}.ini" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    fi
    [[ ! -x "${targetdir}/${script}" ]] && (chmod +x "${targetdir}/${script}" || error "$(eval_gettext "Set executable permission was unsuccessful for file \${targetdir}/\${script}! Maybe it need higher privileges!")")
    actpwd=$(pwd) && cd "${sourcedir}"
    find locale/ -name "${script}.mo" -print0 | xargs -0 cp --parents --target-directory="${localetargetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    cd ${actpwd}
    # Save localetargetdir for removing
    ini_val "${targetdir}/${script}.ini" install.locale "${localetargetdir}"
    debug "$(eval_gettext "Installation file \${script} was succesful to \${targetdir}")"
  done

  for lib in ${libraries}; do
	  [[ "${lib}" = *".."* ]] && emergency "$(eval_gettext "Installation unsuccessful: unsupported filename (\$lib)")"
    if [[ "${force}" = "1" ]]; then
	    cp -f "${libsourcedir}/${lib}" "${libtargetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    else
	    cp -i "${libsourcedir}/${lib}" "${libtargetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    fi
    find "${localesourcedir}" -name "${script}.mo" -print0 | xargs -0 cp --parents --target-directory="${localetargetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    debug "$(eval_gettext "Installation file \${lib} was succesful to \${libtargetdir}")"
  done

  for payload in ${payloads}; do
    # Check filename can't pipe to upper directory
    [[ "${payload}" = *".."* ]] && emergency "$(eval_gettext "Installation unsuccessful: unsupported filename (\${payload})")"
    cp -i "${sourcedir}/${payload}" "${targetdir}" || emergency "$(gettext "Installation unsuccessful: there was an error during copying files")"
    debug "$(eval_gettext "Installation file \${script} was succesful to \${targetdir}")"
  done

  # Install dependencies
  if [[ -n "${dependencies}" ]]; then
    missingpkgs=$(check_pkgs "${dependencies}")
    if [[ -n "${missingpkgs}" ]]; then 
      debug "$(eval_gettext "Missing dependencies: \${missingpkgs}")"
      install_dependencies "${missingpkgs}" "${force}" || emergency "$(gettext "Installation unsuccessful: there was an error during installing dependencies")"
    fi
  fi

  # Calling thirdparty scripts, if any
  for command in ${thirdparties}; do
    eval "${command}"
  done

  # Calling postinstall scripts, if any
  for command in ${postinst}; do
    eval "${command}"
  done

  info "$(eval_gettext "Installation files was succesful to \${targetdir}")"
}

#-------------------------------------------------------------------------------
# edit_profile: Add script's targetdir to user's ~/.profile file
# Arguments:
#   edit_profile folder
# Returns:
#   return 1 if unsuccessful (there's no folder)
#-------------------------------------------------------------------------------
function edit_profile(){
local folder=${1:-}
  if [[ ! -z "${folder}" ]]; then

      if ! grep -q "${folder}" "${__si_user_home}/.profile"; then
        {
          echo "" 
          echo "# set PATH so it includes user's private bin if it exists - Added by b3bp installer"
          echo "if [ -d \"${folder}\" ] ; then"
          echo "    PATH=\"${folder}:\$PATH\" "
          echo "fi" 
        } >> "${__si_user_home}/.profile"
	warning "$(gettext "~/.profile was updated, please login again or run 'source ~/.profile' command to reload PATH variable!")"
        return 0 
      fi

  fi
  return 1
}

function check_dependencies() {
local sourcedir=${1:-}
local inifile=${2:-}
local force=${2:-0}
local dependencies=$( get_ini_val "${inifile}" "install.dependencies" )
local preinst=$( get_ini_val "${inifile}" "install.preinst" )
local postinst=$( get_ini_val "${inifile}" "install.postinst" )

  if [[ ! -z "${dependencies}" ]]; then
    missingpkgs=$(check_pkgs "${dependencies}")
    if [[ ! -z "${missingpkgs}" ]]; then
        debug "$(eval_gettext "Missing dependencies: \${missingpkgs}")"
        if ask "$(eval_gettext "Following packages are missing: \${missingpkgs}, would you like to install them?")" "Y"; then

        # Calling preinstall scripts, if any
        for command in ${preinst}; do
          eval "${command}"
        done

	install_dependencies "${missingpkgs}" "${force}" || emergency "$(gettext "Installation unsuccessful: there was an error during installing dependencies")"

        # Calling postinstall scripts, if any
        for command in ${postinst}; do
          eval "${command}"
        done

      fi
    fi
  fi
}
#-------------------------------------------------------------------------------
# Main function: Determine targetdir based on OS-type and ini-values, then call
# install_files and edit_profile methods
# Arguments:
#   None
# Returns:
#   exit 1, if unsupported OS detected
#-------------------------------------------------------------------------------
function main() {
local sourcedir="${__si_arg_s}"
local force="${__si_arg_f}"

  # Check supported OS
  if [[ "${__osfamily}" = "unknown" ]]; then
	  debug "$(gettext "Unsupported operating system. Installation is not possible.")"

    # exit 1
    display_info "$(gettext "Unsupported operating system. Installation is not possible.")" "$(gettext "Install script manually: 
    * Copy the script and the lib folder to your PATH.
    * Copy to locale folder to your locale folder.
    * Install dependencies.")"
  fi

  if [[ "${__si_arg_c:?}" = "0" ]] ; then   
    __si_arg_t=$(sed "s|~|$HOME|g" <<< "${__si_arg_t:-}") # Workaround for such cases: "~/path/to/file"
    defined_targetdir="${__si_arg_t:-Not defined}"
    targetdir=$([[ $EUID != 0 ]] && echo "${__si_arg_t:-$__si_user_home/.local/bin}" || echo "${__si_arg_t:-/usr/local/bin}")  
    targetdirtext=$([[ $EUID != 0 ]] && sed "s|$HOME|\$HOME|g" <<< "${__si_arg_t:-$__si_user_home/.local/bin}" || sed "s|$HOME|\$HOME|g" <<< "${__si_arg_t:-}")
    localedir=$([[ $EUID != 0 ]] && echo "${__si_arg_t:-$__si_user_home/.local/share}" || echo "${__si_arg_t:-/usr/local/share/locale}")
    inifile="${__si_arg_i:-$sourcedir/install.ini}"

    debug "$(eval_gettext "User's home dir: \${__si_user_home}")"
    debug "$(eval_gettext "Source dir: \${sourcedir}")"
    debug "$(eval_gettext "Defined target dir: \${defined_targetdir}")"
    debug "$(eval_gettext "Target directory, to the script will install: \${targetdir}")"
    debug "$(eval_gettext "Target directory, which is added to ~/.profile file: \${targetdirtext}")"
    debug "$(eval_gettext "Target directory for locale files: \${localedir}")"
    debug "$(eval_gettext "Ini-file: \${inifile}")"

    # Install files and edit ~/.profile file
    install_files "${sourcedir}" "${inifile}" "${targetdir}" "${localedir}" "${force}"
    edit_profile "${targetdirtext}" && source "${__si_user_home}/.profile" && export PATH
 
  else
     # Check dependencies
     check_dependencies "${sourcedir}" "${inifile}"
  fi

}

#===============================================================================
# Main section
#===============================================================================

#-------------------------------------------------------------------------------
# Parse usage string
#-------------------------------------------------------------------------------
while read -r __si_tmp_line; do
  if [[ "${__si_tmp_line}" =~ ^- ]]; then
    # fetch single character version of option string
    __si_tmp_opt="${__si_tmp_line%% *}"
    __si_tmp_opt="${__si_tmp_opt:1}"

    # fetch long version if present
    __si_tmp_long_opt=""

    if [[ "${__si_tmp_line}" = *"--"* ]]; then
      __si_tmp_long_opt="${__si_tmp_line#*--}"
      __si_tmp_long_opt="${__si_tmp_long_opt%% *}"
    fi

    # map opt long name to+from opt short name
    printf -v "__si_tmp_opt_long2short_${__si_tmp_long_opt//-/_}" '%s' "${__si_tmp_opt}"
    printf -v "__si_tmp_opt_short2long_${__si_tmp_opt}" '%s' "${__si_tmp_long_opt//-/_}"

    # check if option takes an argument
    if [[ "${__si_tmp_line}" =~ \[.*\] ]]; then
      __si_tmp_opt="${__si_tmp_opt}:" # add : if opt has arg
      __si_tmp_init=""  # it has an arg. init with ""
      printf -v "__si_tmp_has_arg_${__si_tmp_opt:0:1}" '%s' "1"
    elif [[ "${__si_tmp_line}" =~ \{.*\} ]]; then
      __si_tmp_opt="${__si_tmp_opt}:" # add : if opt has arg
      __si_tmp_init=""  # it has an arg. init with ""
      # remember that this option requires an argument
      printf -v "__si_tmp_has_arg_${__si_tmp_opt:0:1}" '%s' "2"
    else
      __si_tmp_init="0" # it's a flag. init with 0
      printf -v "__si_tmp_has_arg_${__si_tmp_opt:0:1}" '%s' "0"
    fi
    __si_tmp_opts="${__si_tmp_opts:-}${__si_tmp_opt}"
  fi

  [[ "${__si_tmp_opt:-}" ]] || continue

  if [[ "${__si_tmp_line}" =~ ^"${__si_defaulttext}"= ]] || [[ "${__si_tmp_line}" =~ \.\ *"${__si_defaulttext}"= ]]; then
    __si_tmp_default="1"
    __si_tmp_defaulttext="${__si_defaulttext}"
  elif [[ "${__si_tmp_line}" =~ ^Default= ]] || [[ "${__si_tmp_line}" =~ \.\ *Default= ]]; then
    __si_tmp_default="1"
    __si_tmp_defaulttext=Default
  else
    [[ ${__si_tmp_default+x} ]] && unset __si_tmp_default
    [[ ${__si_tmp_defaulttext+x} ]] && unset __si_tmp_defaulttext
  fi

  if [[ ${__si_tmp_default:-} = "1" ]]; then
    # ignore default value if option does not have an argument
    __si_tmp_varname="__si_tmp_has_arg_${__si_tmp_opt:0:1}"

    if [[ "${!__si_tmp_varname}" != "0" ]]; then
      __si_tmp_init="${__si_tmp_line##*${__si_tmp_defaulttext}=}"
      __si_tmp_re='^"(.*)"$'
      if [[ "${__si_tmp_init}" =~ ${__si_tmp_re} ]]; then
        __si_tmp_init="${BASH_REMATCH[1]}"
      else
        __si_tmp_re="^'(.*)'$"
        if [[ "${__si_tmp_init}" =~ ${__si_tmp_re} ]]; then
          __si_tmp_init="${BASH_REMATCH[1]}"
        fi
      fi
    fi 
  fi

  if [[ "${__si_tmp_line}" =~ ^"${__si_requiredtext}"\. ]] || [[ "${__si_tmp_line}" =~ \.\ *"${__si_requiredtext}"\. ]] || [[ "${__si_tmp_line}" =~ ^Required\. ]] || [[ "${__si_tmp_line}" =~ \.\ *Required\. ]]; then
    # remember that this option requires an argument
    printf -v "__si_tmp_has_arg_${__si_tmp_opt:0:1}" '%s' "2"
  fi

  printf -v "__si_arg_${__si_tmp_opt:0:1}" '%s' "${__si_tmp_init}"
done <<< "${__si_usage:-}"

#-------------------------------------------------------------------------------
# Parse command-line arguments
#-------------------------------------------------------------------------------
# run getopts only if options were specified in __usage
if [[ "${__si_tmp_opts:-}" ]]; then
  # Allow long options like --this
  __si_tmp_opts="${__si_tmp_opts}-:"

  # Reset in case getopts has been used previously in the shell.
  OPTIND=1

  # start parsing command line
  set +o nounset # unexpected arguments will cause unbound variables
                 # to be dereferenced
  # Overwrite $arg_<flag> defaults with the actual CLI options
  while getopts "${__si_tmp_opts}" __si_tmp_opt; do
    [[ "${__si_tmp_opt}" = "?" ]] && (__si_tmp_params="${*}"; display_info "$(eval_gettext "Invalid use of script: \${__si_tmp_params}")" "\${__si_usage}" "\${__si_helptext}")

    if [[ "${__si_tmp_opt}" = "-" ]]; then
      # OPTARG is long-option-name or long-option=value
      if [[ "${OPTARG}" =~ .*=.* ]]; then
        # --key=value format
        __si_tmp_long_opt=${OPTARG/=*/}
        # Set opt to the short option corresponding to the long option
        __si_tmp_varname="__si_tmp_opt_long2short_${__si_tmp_long_opt//-/_}"
        printf -v "__si_tmp_opt" '%s' "${!__si_tmp_varname}"
        OPTARG=${OPTARG#*=}
      else
        # --key value format
        # Map long name to short version of option
        __si_tmp_varname="__si_tmp_opt_long2short_${OPTARG//-/_}"
        printf -v "__si_tmp_opt" '%s' "${!__si_tmp_varname}"
        # Only assign OPTARG if option takes an argument
        __si_tmp_varname="__si_tmp_has_arg_${__si_tmp_opt}"
        printf -v "OPTARG" '%s' "${@:OPTIND:${!__si_tmp_varname}}"
        # shift over the argument if argument is expected
        ((OPTIND+=__si_tmp_has_arg_${__si_tmp_opt}))
      fi
      # we have set opt/OPTARG to the short value and the argument as OPTARG if it exists
    fi
    __si_tmp_varname="__si_arg_${__si_tmp_opt:0:1}"
    __si_tmp_default="${!__si_tmp_varname}"

    __si_tmp_value="${OPTARG}"
    if [[ -z "${OPTARG}" ]]; then
      __si_tmp_value=$((__si_tmp_default + 1))
    fi

    printf -v "${__si_tmp_varname}" '%s' "${__si_tmp_value}"
    debug "cli arg ${__si_tmp_varname} = (${__si_tmp_default}) -> ${!__si_tmp_varname}"
  done
  set -o nounset # no more unbound variable references expected

  shift $((OPTIND-1))

  if [[ "${1:-}" = "--" ]] ; then
    shift
  fi
fi

#-------------------------------------------------------------------------------
# Helper functions
#-------------------------------------------------------------------------------
if [[ "${__si_arg_h:?}" = "1" ]]; then
  # Help exists with code 1
  display_info "$(eval_gettext "Help using \${__si_base}")" "${__si_usage}" "${__si_helptext}"
fi

if [[ "${__si_arg_V:?}" = "1" ]]; then
  # Version exists with code 1
  display_info "${__si_name}" "${__si_version}" "${__si_license}"
fi

#-------------------------------------------------------------------------------
# Validate required arguments
#-------------------------------------------------------------------------------
[[ "${LOG_LEVEL:-}" ]] || emergency "$(gettext "Cannot continue without LOG_LEVEL.")"

#-------------------------------------------------------------------------------
# Validate required option arguments
#-------------------------------------------------------------------------------
for __si_tmp_varname in ${!__si_tmp_has_arg_*}; do
  # validate only options which required an argument
  [[ "${!__si_tmp_varname}" = "2" ]] || continue

  __si_tmp_opt_short="${__si_tmp_varname##*_}"
  __si_tmp_varname="__si_arg_${__si_tmp_opt_short}"
  [[ "${!__si_tmp_varname}" ]] && continue

  __si_tmp_varname="__si_tmp_opt_short2long_${__si_tmp_opt_short}"
  printf -v "__si_tmp_opt_long" '%s' "${!__si_tmp_varname}"
  [[ "${__si_tmp_opt_long:-}" ]] && __si_tmp_opt_long=" (--${__si_tmp_opt_long//_/-})"

  display_info "$(eval_gettext "Option -\${__si_tmp_opt_short}\${__si_tmp_opt_long:-} requires an argument")" "${__si_usage}" "${__si_helptext}"
done

#-------------------------------------------------------------------------------
# Cleanup temporary variables 
#-------------------------------------------------------------------------------
for __tmp_varname in ${!__si_tmp_*}; do
  unset -v "${__tmp_varname}"
done

unset -v __tmp_varname

#-------------------------------------------------------------------------------
# Externally supplied __si_usage. Nothing else to do here
#-------------------------------------------------------------------------------
if [[ "${__si_external_usage:-}" == 1 ]]; then
  unset -v __si_external_usage
  return
fi

#-------------------------------------------------------------------------------
# Signal trapping and backtracing
#-------------------------------------------------------------------------------
function __si_cleanup_before_exit () {
  info "$(gettext "Cleaning up. Done")"
}
trap __si_cleanup_before_exit EXIT

# requires `set -o errtrace`
__si_err_report() {
  local error_code
  error_code=${?}
  function=${1}
  line=${2}

  error "$(eval_gettext "Error in \${__si_file} in function \${function} on line \${line}")"
  exit ${error_code}
}
# Uncomment the following line for always providing an error backtrace
# trap '__si_err_report "${FUNCNAME:-.}" ${LINENO}' ERR

#-------------------------------------------------------------------------------
# Call internal functions
#-------------------------------------------------------------------------------
# debug mode
if [[ "${__si_arg_d:?}" = "1" ]]; then
  set -o xtrace
  LOG_LEVEL="7"
  # Enable error backtracing
  trap '__si_err_report "${FUNCNAME:-.}" ${LINENO}' ERR
fi

# verbose mode
if [[ "${__si_arg_v:?}" = "1" ]]; then
  set -o verbose
fi

# no color mode
if [[ "${__si_arg_n:?}" = "1" ]]; then
  NO_COLOR="true"
fi

#-------------------------------------------------------------------------------
# Runtime
#-------------------------------------------------------------------------------
if [[ "${__si_srcd:-}" == 0 ]]; then
  main
fi

#===============================================================================
# END OF FILE
#===============================================================================
